function out = rd_DY_wind(fn)
% function out = rd_DY_att(fn)
% 
% read wind data generated by Discovery instrumentation
% (should work for Applanix, Phins and Seapath)
%
% out contains time, head, heave, pitch, roll
%
pkg load netcdf

out.time = ncread(fn, 'time'); #"days since 1899-12-30 00:00:00 UTC"
out.time = out.time + datenum([1899 12 30 00 00 00]);
out.wdir = ncread(fn, 'direct'); # "degree";
out.wspd = ncread(fn, 'speed');  # units = "m/s";
out.airt = ncread(fn, 'airtemp'); # units = "degree_Celcius"
out.humid = ncread(fn, 'humid'); # units = %
	
	
endfunction