function out = rd_DY_att(fn)
% function out = rd_DY_att(fn)
% 
% read attitude data generated by Discovery instrumentation
% (should work for Applanix, Phins and Seapath)
%
% out contains time, head, heave, pitch, roll
%
pkg load netcdf

out.time = ncread(fn, 'time'); #"days since 1899-12-30 00:00:00 UTC"
out.time = out.time + datenum([1899 12 30 00 00 00]);
out.head = ncread(fn, 'head');
out.heave = ncread(fn, 'heave');
out.pitch = ncread(fn, 'pitch');
out.roll = ncread(fn, 'roll');
	
	
endfunction